### ISSUE TITLE
Multi User Plugin Incompatibility

### ISSUE THREAD

**Issue by bensayersllc** [johnstray/gs-blog#52]
Here's the error I receive with the latest version of Get Simple Blog (from GitHub) and the latest version of Multi User (from Extend) with GetSimple 3.3.4 installed.

<code>Warning: MultiUser::getUserPermission() [multiuser.getuserpermission]: Node no longer exists in /mywebdirectory/plugins/user-managment.php on line 195</code>

**Comment by johnstray** [comment]
I'll have to look into this one. Might be an issue with the MultiUser plugin though and not with the blog.

**Comment by johnstray** [comment]
As far as I can tell so far, this appears to be an issue with the Multi-User plugin. It does not generate users permissions until you edit the user and save their settings (even without making changes). Once the user permissions have been saved, the php warnings disappear.

I might need to have a chat with the author of the Multi-User plugin to determine how his plugin works exactly, where the issue actually occurs, and the best method to resolve it.

For now, just edit each user and save their permissions. This will remove the php warnings.

**Comment by johnstray** [comment]
Upon further investigation, negotiation might not be possible. The author of that plugin is that same as the original author of this plugin. He has not been seen around for about 2 years, which is why I took over this plugin in the first place.

So, I will investigate the interoperability of the two plugins and see what I can figure out. This might take a few weeks though.

**Comment by bensayersllc** [comment]
Thanks for looking into it, John. I wish they could just make Multi-User part of the GS core. 

Cheers!

**Comment by johnstray** [comment]
I agree! One would think that it's logical to add that to the core.

**Comment by johnstray** [comment]
Ok, so this can't be fixed as the bug is in the way that the Multi-User plugin handles XML files when checking user permissions. This php warning pops up when checking for property existence in a SimpleXML tree. The only way this can be fixed properly is by modification of the Multi-User plugin, something that can't be done at this stage. For now, everyone will just have to use the above mentioned work-around.

Reference - StackOverflow: http://stackoverflow.com/questions/15101478/check-for-propertys-existence-without-getting-node-no-longer-exists-warning
