### ISSUE TITLE
Update Check Error

### ISSUE THREAD

**Issue by bensayersllc** [johnstray/gs-blog#53]
Hi John, sorry for the multiple posts - trying to keep things organized. I get the following error when I click "update Check".

<code>Warning: file_get_contents() [function.file-get-contents]: http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/bsayers/public_html/dev/bsllc2015/plugins/gs-blog/inc/versionCheck.php on line 26</code>

<code>Warning: file_get_contents(http://get-simple.info/api/extend/?id=810) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/bsayers/public_html/dev/bsllc2015/plugins/gs-blog/inc/versionCheck.php on line 26</code>

**Comment by johnstray** [comment]
This one is not actually a bug. That error is caused by a configuration error in your server environment. For versionCheck to work correctly, you need to enable 'allow_url_fopen' in your php server environment. This can be changed in your php.ini file.

**Comment by bensayersllc** [comment]
Thanks for all your input, John - it's most appreciated. 

My host had the following warning which is a bit concerning. I guess not knowing if I have the latest version isn't a big deal. Will leaving the directive disabled affect anything else with the plugin?

"The allow_url_fopen directive is disabled by default. You should be aware of the security implications of enabling the allow_url_fopen directive. PHP scripts that can access remote files are potentially vulnerable to arbitrary code injection."
https://www.a2hosting.com/kb/developer-corner/php/using-php.ini-directives/php-allow-url-fopen-directive

**Comment by johnstray** [comment]
It won't have any other adverse effect on the plugin having the directive disabled. 

It's probably not the best method I could have chosen to implement the function and I might actually look into changing it so that it uses http post instead of a file get contents method. It safer and doesn't rely on that directive being enabled. 

Thanks for all your feedback thus far, you've found a few issues that probably would have gone unnoticed otherwise. It's greatly appreciated.

**Comment by bensayersllc** [comment]
No problem at all, I've been hoping someone would take over the Blog plugin. Kudos to you, sir!
