### ISSUE TITLE
"read more" broken in show_blog_recent_posts()

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#84]
The function creates an anchor at the end of the excerpt, but the anchor text is always 1 instead of READ_FULL_ARTICLE.
Reason: in line 335, `$read_more` (the boolean...) is used instead of `i18n_r(BLOGFILE.'/READ_FULL_ARTICLE')`

**Comment by johnstray** [comment]
Line 310: `* @param $read_more      (string) A text string to show for "Read More" link. Not shown if null`

**Comment by johnstray** [comment]
Hmmm... Should probably have mentioned this in the Help section...

**Comment by johnstray** [comment]
I think I might change this so that it does accept a boolean and set it to use a new language string for the text.

Not related to this issue, but I think `show_blog_recent_posts()` could also have a `$limit` variable that can override the settings.

**Comment by gschintgen** [comment]
Oops, right, I don't even know how I got the idea that `$read_more` was a boolean. Probably because of the documentation which passed "true" and the resulting "1" that was shown.
An additional string would have the advantage that it could also be used for the main blog page. (#85)

**Comment by johnstray** [comment]
The help page in admin has it as taking a boolean. I'm changing it so that it can take either a boolean or a string. If a boolean is provided, `true` will show the default read more text (added to the language file), `false` will show nothing. If a string is provided, the string will show. Having both methods means that compatibility is provided with whatever method was used in the past.

**Comment by gschintgen** [comment]
great!
